### ISSUE TITLE
unable to contact

### ISSUE THREAD

**Issue by sanjaix21** [07Sushant/07Sushant#1]
I tried reaching out to you through instagram and twitter but your account do not allow dm. 
I tried contact you regarding making a common repo for updating answers. 
If you're intrested dm me. 
Instagram - [@mr.x.robot](https://instagram.com/mr.x.robot)
Twitter - [@flightman69](https://x.com/flightman69)

**Comment by 07Sushant** [comment]
You can contact me  on 
07Sushant LinkedIn
Instagram 
Twitter

**Comment by sanjaix21** [comment]
> 

I tried. But your twitter is private can't send any dm
Your insta is also private. Can't send message there too.
I don't want to contact through LinkedIn.

**Comment by 07Sushant** [comment]
oh
